### ISSUE TITLE
Could you hide process from Windows list?

### ISSUE THREAD

**Issue by letuan1206** [adamhlt/Basic-Rootkit#1]
Hi,

Could you make it work on the windows list? 

Could you see on this video: https://youtu.be/TX34pEmsxfA

**Comment by adamhlt** [comment]
Hello, 

If I have time, I'll add more features, hide windows and hook other process enumeration methods.

**Comment by letuan1206** [comment]
> Hello,
> 
> If I have time, I'll add more features, hide windows and hook other process enumeration methods.

It's great and waiting. Thank you

**Comment by adamhlt** [comment]
After some research, there is no universal method to hook. Of course you can hook the callback function set by `EnumWindows` but you have to do it for every program.

If you really want to hide a window from every process you have to use a driver and make a more advanced rootkit in Ring0.
